### ISSUE TITLE
How to exclude certain classes

### ISSUE THREAD

**Issue by mhamilton723** [sbt/sbt-unidoc#85] opened 2021-06-18 23:37 UTC
Hey I have an isssue where i cannot generate docs for my multi-project because of a shared class of BuildInfo:

```
[info] Main Scala API documentation to C:\code\mmlspark\target\scala-2.12\sbt-1.0\unidoc...
[error] C:\code\mmlspark\core\target\scala-2.12\sbt-1.0\src_managed\main\sbt-buildinfo\BuildInfo.scala:6:13: BuildInfo is already defined as case class BuildInfo
[error] case object BuildInfo {
[error]             ^
[error] C:\code\mmlspark\deep-learning\target\scala-2.12\sbt-1.0\src_managed\main\sbt-buildinfo\BuildInfo.scala:6:13: BuildInfo is already defined as case class BuildInfo
[error] case object BuildInfo {
[error]             ^
[error] C:\code\mmlspark\lightgbm\target\scala-2.12\sbt-1.0\src_managed\main\sbt-buildinfo\BuildInfo.scala:6:13: BuildInfo is already defined as case class BuildInfo
[error] case object BuildInfo {
[error]             ^
[error] C:\code\mmlspark\opencv\target\scala-2.12\sbt-1.0\src_managed\main\sbt-buildinfo\BuildInfo.scala:6:13: BuildInfo is already defined as case class BuildInfo
[error] case object BuildInfo {
[error]             ^
[error] C:\code\mmlspark\target\scala-2.12\sbt-1.0\src_managed\main\sbt-buildinfo\BuildInfo.scala:6:13: BuildInfo is already defined as case class BuildInfo
[error] case object BuildInfo {
[error]             ^
[error] C:\code\mmlspark\vw\target\scala-2.12\sbt-1.0\src_managed\main\sbt-buildinfo\BuildInfo.scala:6:13: BuildInfo is already defined as case class BuildInfo
[error] case object BuildInfo {
[error]             ^
[info] No documentation generated with unsuccessful compiler run
```

Is there any way to ignore this class in the generation?

**Comment by eed3si9n** [comment] 2021-06-19 00:46
You can try filtering them out of `Compile / unidoc / sources`.

**Comment by mhamilton723** [comment] 2021-06-21 18:07
Thanks @eed3si9n for the fast reply! I am having a bit of trouble figuring out the right magic to put in here:
this is what I have added to my root project with no dice yet. (the BuildInfo class is generated by BuildInfo sbt plugin and should be considered a "managedSource")

```
lazy val root = (project in file("."))
  .aggregate(core, deepLearning, cognitive, vw, lightgbm, opencv)
  .dependsOn(core, deepLearning, cognitive, vw, lightgbm, opencv)
  .enablePlugins(BuildInfoPlugin && ScalaUnidocPlugin && SbtPlugin)
  .disablePlugins(CodegenPlugin)
  .settings(settings ++ Seq(
    name := "mmlspark",
    buildInfoKeys += datasetDir,
    (Compile / unidoc / sources) := (Compile / unmanagedSources).toTask.value.distinct,

  ))
```

**Comment by eed3si9n** [comment] 2021-06-21 18:24
I think the problem is that you're not following the guideline of sbt-buildinfo.

Try putting them into different package names like:

```scala
    buildInfoPackage := "com.example.core",
```

```scala
    buildInfoPackage := "com.example.app",
```

if you have multiple of them.

**Comment by mhamilton723** [comment] 2021-06-21 22:39
Thanks, though i could not figure out how to exclude classes I refactored my lib to avoid multiple buildInfo classes and no longer face this issue!

**Comment by eed3si9n** [comment] 2021-06-22 15:36
This is something what I had in mind:

```scala
Compile / unidoc / sources ~= { case x => x }
```

I'm closing this for now.

**Closed by eed3si9n** 2021-06-22 15:36 UTC
